# Generated by Django 3.1.7 on 2021-02-24 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acreditation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название СМИ')),
                ('format', models.CharField(max_length=150, verbose_name='Формат выхода материала')),
                ('name', models.CharField(max_length=150, verbose_name='Ф.И.О.')),
                ('date', models.DateTimeField(verbose_name='Дата выхода материала')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.PositiveSmallIntegerField(blank=True, help_text='+998', null=True, verbose_name='Телефон')),
                ('info', models.TextField(verbose_name='Информация')),
                ('list', models.TextField(verbose_name='Список съемочного оборудования')),
                ('files', models.FileField(upload_to='materials/', verbose_name='Файлы')),
            ],
            options={
                'verbose_name': 'Аккредитация',
                'verbose_name_plural': 'Аккредитации',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категории')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование организации')),
                ('face', models.CharField(max_length=150, verbose_name='Контактное лицо')),
                ('phone', models.PositiveSmallIntegerField(blank=True, help_text='+998', null=True, verbose_name='Телефон')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата выхода материала')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('files', models.FileField(upload_to='contact/', verbose_name='Файлы')),
            ],
            options={
                'verbose_name': 'Связь с нами',
                'verbose_name_plural': 'Связь с нами',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Оглавление')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nat.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Новости и Мероприятия',
                'verbose_name_plural': 'Новости и Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Оглавление')),
                ('description', models.TextField(verbose_name='Описание')),
                ('add', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nat.post', verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'Дополнительный текст',
                'verbose_name_plural': 'Дополнительный текст',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название организации')),
                ('images', models.ImageField(upload_to='sponsors/', verbose_name='Логотип')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nat.post', verbose_name='Организации')),
            ],
            options={
                'verbose_name': 'Спонсор',
                'verbose_name_plural': 'Спонсоры',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Краткая информация')),
                ('image', models.ImageField(upload_to='people/', verbose_name='Изображение')),
                ('perscat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nat.category', verbose_name='')),
                ('personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nat.post', verbose_name='Персонал')),
            ],
            options={
                'verbose_name': 'Персонал',
                'verbose_name_plural': 'Персонал',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Логотип')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nat.post', verbose_name='Главные картинки')),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nat.sponsor', verbose_name='Логотипы Организации')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Фото Галлерея')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nat.post', verbose_name='Галлерея')),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nat.sponsor', verbose_name='Спонсоры')),
            ],
            options={
                'verbose_name': 'Галлерея',
                'verbose_name_plural': 'Галлерея',
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Оглавление')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание файла')),
                ('file', models.FileField(upload_to='files/', verbose_name='Документы (PDF, WORD...)')),
                ('documents', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nat.post', verbose_name='Документы к')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
