# Generated by Django 3.1.7 on 2021-02-23 06:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='name',
        ),
        migrations.AddField(
            model_name='personal',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=500, verbose_name='Краткая информация'),
            preserve_default=False,
        ),
    ]
