# Generated by Django 3.1.7 on 2021-02-23 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nat', '0003_files'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
    ]
