# Generated by Django 3.1.7 on 2021-02-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nat', '0004_auto_20210224_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Документы (PDF, WORD...)'),
        ),
    ]
