# Generated by Django 3.1.7 on 2021-02-23 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nat', '0004_auto_20210223_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='documents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nat.post', verbose_name='Документы к'),
        ),
    ]
