# Generated by Django 3.1.7 on 2021-02-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nat', '0005_auto_20210223_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acreditation',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название СМИ'),
        ),
    ]
