# Generated by Django 3.1.7 on 2021-02-24 19:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nat', '0006_remove_gallery_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Краткая информация'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personal',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Фамилия Имя'),
        ),
    ]
