# Generated by Django 3.1.7 on 2021-02-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nat', '0006_auto_20210223_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование организации')),
                ('face', models.CharField(max_length=150, verbose_name='Контактное лицо')),
                ('phone', models.PositiveSmallIntegerField(blank=True, help_text='+998', null=True, verbose_name='Телефон')),
                ('date', models.DateTimeField(verbose_name='Дата выхода материала')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('files', models.FileField(upload_to='contact/', verbose_name='Файлы')),
            ],
            options={
                'verbose_name': 'Связь с нами',
                'verbose_name_plural': 'Связь с нами',
            },
        ),
    ]
