# Generated by Django 3.1.7 on 2021-02-23 13:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nat', '0007_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='shots',
        ),
        migrations.AddField(
            model_name='files',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание файла'),
        ),
        migrations.AddField(
            model_name='files',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='Оглавление'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='perscat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nat.category', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата выхода материала'),
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Оглавление')),
                ('description', models.TextField(verbose_name='Описание')),
                ('add', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nat.post', verbose_name='Дополнительная информация')),
            ],
        ),
    ]
