# Generated by Django 3.1.7 on 2021-02-23 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nat', '0008_auto_20210223_1803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='text',
            options={'verbose_name': 'Дополнительный текст', 'verbose_name_plural': 'Дополнительный текст'},
        ),
    ]
